# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose-2.4.yml up -d
version: '3.3'
# docker-compose -f docker-compose-app.yml up -d
# 你需要修改system为你自身系统的仓库名
services:
  weave:
    image: crpi-5tzwiznwaw34lfca.cn-guangzhou.personal.cr.aliyuncs.com/aseubel/themis:latest
    container_name: themis
    restart: on-failure
    ports:
      - "611:611"
    environment:
      - TZ=PRC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/themis?serverTimezone=UTC&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - SERVER_PORT=611
      - JWT_SECRET=YOUR_JWT_SECRET
      - aliyun-access-key-id=YOUR_ACCESS_KEY_ID
      - aliyun-access-key-secret=YOUR_ACCESS_KEY_SECRET
      - aliyun-template-code=YOUR_TEMPLATE_CODE
      - aliyun-sign-name=YOUR_SIGN_NAME
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
